theme = "everforest_dark_hard"

[editor]
true-color = true
line-number = "relative"
cursorline = true
color-modes = true
idle-timeout = 10

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.indent-guides]
render = true
character = "┆"